In [1]:
#zoom camp 2022

In [2]:
import os 
os.getcwd()

'C:\\Users\\user\\elite_python_learning'

In [3]:
#homework intro

In [4]:
#question 1

import numpy as np
np.version.version

'1.20.3'

In [5]:
import pandas as pd

In [6]:
car_price_data = pd.read_csv("car_price_data.csv")
car_price_data

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [7]:
#question 2

#ans = 11914

In [9]:
#question 3
#Who are the most frequent car manufacturers (top-3) according to the dataset?

#answer = "Chevrolet, Ford, Volkswagen"
car_price_data['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker              3
Genesis             3
Bugatti             3
Name: Make, dtype: int64

In [118]:
#question 4
#What's the number of unique Audi car models in the dataset?

#ans = 34
car_price_data[
    car_price_data["Make"] == "Audi" 
].nunique()

Make                   1
Model                 34
Year                  20
Engine Fuel Type       5
Engine HP             40
Engine Cylinders       6
Transmission Type      3
Driven_Wheels          2
Number of Doors        2
Market Category       15
Vehicle Size           3
Vehicle Style          6
highway MPG           23
city mpg              18
Popularity             1
MSRP                 234
dtype: int64

In [18]:
#Question 5
#How many columns in the dataset have missing values?

# answer is 5colomns
car_price_data.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [20]:
#Question 6
#Find the median value of "Engine Cylinders" column in the dataset.
#Next, calculate the most frequent value of the same "Engine Cylinders".
#Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
#Now, calculate the median value of "Engine Cylinders" once again.

In [21]:
#Find the median value of "Engine Cylinders" column in the dataset.
car_price_data['Engine Cylinders'].median()

6.0

In [22]:
#calculate the most frequent value of the same "Engine Cylinders"
car_price_data['Engine Cylinders'].mode()

0    4.0
dtype: float64

In [37]:
#Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
fillmissing = car_price_data['Engine Cylinders'].fillna(4.0)
fillmissing

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ...
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [41]:
#Now, calculate the median value of "Engine Cylinders" once again.
fillmissing.median()

6.0

In [ ]:
#Question 7
#Select all the "Lotus" cars from the dataset.
#Select only columns "Engine HP", "Engine Cylinders".
#Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
#Get the underlying NumPy array. Let's call it X.
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#Invert XTX.
#Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#What's the value of the first element of w?
#Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [43]:
#Select all the "Lotus" cars from the dataset.
car_price_data[
    car_price_data["Make"] == "Lotus"
]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
3912,Lotus,Elise,2009,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,43995
3913,Lotus,Elise,2009,premium unleaded (required),218.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3914,Lotus,Elise,2009,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,47250
3915,Lotus,Elise,2010,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,47250
3916,Lotus,Elise,2010,premium unleaded (required),218.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3917,Lotus,Elise,2011,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,51845
3918,Lotus,Elise,2011,premium unleaded (required),217.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3919,Lotus,Elise,2011,premium unleaded (required),217.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,57950
4216,Lotus,Esprit,2002,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,89825
4217,Lotus,Esprit,2003,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,90825
4218,Lotus,Esprit,2004,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,93225
4257,Lotus,Evora 400,2017,premium unleaded (required),400.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,39,21,613,91900
4258,Lotus,Evora 400,2017,premium unleaded (required),400.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,39,21,613,91900
4259,Lotus,Evora,2011,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,27,18,613,64000
4260,Lotus,Evora,2011,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,65500
4261,Lotus,Evora,2013,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,66800
4262,Lotus,Evora,2013,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,77100
4263,Lotus,Evora,2013,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,78600
4264,Lotus,Evora,2013,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,68300
4265,Lotus,Evora,2014,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,78750
4266,Lotus,Evora,2014,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,68750
4267,Lotus,Evora,2014,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,79980
4268,Lotus,Evora,2014,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,69980
4292,Lotus,Exige,2009,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,74995
4293,Lotus,Exige,2009,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4294,Lotus,Exige,2010,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4295,Lotus,Exige,2011,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4296,Lotus,Exige,2011,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,70750
4297,Lotus,Exige,2011,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,74950

In [58]:
#Select only columns "Engine HP", "Engine Cylinders".
hp_cylinder = car_price_data[['Engine HP', 'Engine Cylinders']]
hp_cylinder

       Engine HP  Engine Cylinders
0          335.0               6.0
1          300.0               6.0
2          300.0               6.0
3          230.0               6.0
4          230.0               6.0
...          ...               ...
11909      300.0               6.0
11910      300.0               6.0
11911      300.0               6.0
11912      300.0               6.0
11913      221.0               6.0

[11914 rows x 2 columns]

In [75]:
#Now drop all duplicated rows using drop_duplicates method 
remove_dup =hp_cylinder.drop_duplicates(keep = False)
remove_dup

       Engine HP  Engine Cylinders
622        661.0              12.0
670        402.0              12.0
720        535.0              12.0
736        300.0               4.0
761        372.0              12.0
963        500.0               6.0
1132       500.0              12.0
1341       152.0               6.0
1431       456.0               8.0
2061       451.0               8.0
2166       553.0               8.0
2167       453.0               8.0
2534       102.0               4.0
2858       572.0               8.0
3522       435.0              12.0
4024       660.0              12.0
4467       240.0               8.0
4793       123.0               3.0
5205       361.0               8.0
5286       362.0               8.0
5601       565.0               6.0
5777       580.0              10.0
5778         NaN               NaN
6249        66.0               3.0
6320       303.0               4.0
6436       424.0               6.0
6438       552.0              10.0
6478       278.0               8.0
6599       493.0               6.0
6802       116.0               6.0
6803       151.0               4.0
6998       592.0               8.0
6999       616.0               8.0
7063       670.0              12.0
7263       573.0               6.0
7991       540.0              10.0
8373       154.0               NaN
8486       650.0              12.0
9662       557.0               8.0
9689       622.0               8.0
10013      142.0               4.0
10528      310.0              10.0
11506      355.0               6.0
11640      197.0               5.0
11792       97.0               4.0

In [94]:
#Get the underlying NumPy array. Let's call it X.
X =np.array([[1, 2, 3], [4, 5, 6], [4,5,7]])

X

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 7]])

In [95]:
#transpose of X
XT = np.transpose(x)
XT

array([[1, 4, 4],
       [2, 5, 5],
       [3, 6, 7]])

In [97]:
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = XT*X
XTX

array([[ 1,  8, 12],
       [ 8, 25, 30],
       [12, 30, 49]])

In [103]:
#Invert XTX.
inverse_XTX =(np.linalg.inv(XTX))
inverse_XTX

array([[-0.49923195,  0.04915515,  0.0921659 ],
       [ 0.04915515,  0.14592934, -0.10138249],
       [ 0.0921659 , -0.10138249,  0.05990783]])

In [108]:
#Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
y = np.array([[1100, 800, 750], [850, 1300, 1000], [1000, 1300, 800]])
y

array([[1100,  800,  750],
       [ 850, 1300, 1000],
       [1000, 1300,  800]])

In [109]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
k = inverse_XTX * XT
k

array([[-0.49923195,  0.19662058,  0.36866359],
       [ 0.09831029,  0.7296467 , -0.50691244],
       [ 0.2764977 , -0.60829493,  0.41935484]])

In [112]:
#Call the result w.
w = y * k
w

array([[-549.15514593,  157.29646697,  276.49769585],
       [  83.56374808,  948.54070661, -506.9124424 ],
       [ 276.49769585, -790.78341014,  335.48387097]])

In [ ]:
#What's the value of the first element of w?
# ANS = -549.15514593